inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'

inherit_from:
  - .rubocop_strict.yml
