inherit_from:
  - .rubocop_todo.yml

Lint/Debugger:
  Enabled: true
  Exclude: []

RSpec/Focus:
  Enabled: true
  Exclude: []

Rails/Output:
  Enabled: true
  Exclude: []

Rails/FindEach:
  Enabled: true
  Exclude: []

Rails/UniqBeforePluck:
  Enabled: true
  Exclude: []
