default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paymaster_development

test:
  <<: *default
  database: paymaster_test

production:
  <<: *default
  database: paymaster_production
  username: paymaster
  password: <%= ENV['PAYMASTER_DATABASE_PASSWORD'] %>
